<?php

/**
 * @file
 * Cacheflush Cloner module.
 */

/**
 * Implements hook_menu().
 */
function cacheflush_cloner_menu() {

  $items['admin/config/development/cacheflush/clone/%'] = array(
    'title' => 'Clone preset',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cacheflush_cloner_presets_clone', 5),
    'access arguments' => array('cacheflush development clone'),
    'file' => 'cacheflush_cloner.clone.inc',
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cacheflush_cloner_form_cacheflush_list_preset_form_alter(&$form, &$form_state, $form_id) {

  $form['preset_list']['#header']['operations'] = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Operations&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
  foreach ($form['preset_list']['#options'] as $id => $value) {
    if ($id >= 5) {
      $form['preset_list']['#options'][$id]['operations'] = $form['preset_list']['#options'][$id]['operations'] . ' | ' . l(t('Clone'), "admin/config/development/cacheflush/clone/$id");
    }
  }
}
